<?xml version="1.0"?>
<!--

  Copyright (c) 2016, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!--File includes-->
  <xacro:include filename="$(find talos_description)/urdf/deg_to_rad.xacro" />
  <xacro:include filename="$(find talos_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:unless value="$(arg test)">
    <xacro:include filename="$(find talos_description_calibration)/urdf/calibration/calibration_constants.urdf.xacro" />
  </xacro:unless>
  <xacro:if value="$(arg test)">
    <xacro:include filename="$(find talos_description)/test/calibration/calibration_constants.urdf.xacro" />
  </xacro:if>

 <!--Constant parameters-->
  <xacro:property name="torso_max_vel"  value="5.4" />
  <xacro:property name="torso_max_effort"  value="200.0" />
  <xacro:property name="torso_eps"      value="0.02" />

  <xacro:macro name="talos_torso" params="name using_capsule_collision">
    <!--************************-->
    <!--        TORSO_2  (TILT) -->
    <!--************************-->
    <link name="${name}_2_link">
      <xacro:call macro="${name}_2_link_inertial" />

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://talos_description/meshes/torso/torso_2.STL" scale="1 1 1"/>
        </geometry>
        <material name="LightGrey" />
      </visual>

      <xacro:if value="${using_capsule_collision}">
        <xacro:capsule-collision e1="-0.0381908 -4.93875e-05 0.108256" e2="-0.045126 -6.75323e-05 0.298264" rad="0.23584089766240193" clen="0.19013465851723285" rpy="9.54947e-05 -0.0364831 -1.74216e-06" mid="-0.0416584 -5.84599e-05 0.20326" />
      </xacro:if>
      <xacro:unless value="${using_capsule_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://talos_description/meshes/torso/torso_2_collision.STL" scale="1 1 1"/>
          </geometry>
        </collision>
      </xacro:unless>
    </link>


    <!--************************-->
    <!--        TORSO_1  (PAN)  -->
    <!--************************-->
    <link name="${name}_1_link">
      <xacro:call macro="${name}_1_link_inertial" />

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://talos_description/meshes/torso/torso_1.STL" scale="1 1 1"/>
        </geometry>
        <material name="LightGrey" />
      </visual>

      <xacro:if value="${using_capsule_collision}">
        <xacro:capsule-collision e1="-0.00232934 -0.0104948 -0.01235" e2="-0.00187524 0.0100705 -0.0118019" rad="0.091952314418329517" clen="0.020577608942189702" rpy="-1.54415 0.0220698 -0.0214895" mid="-0.00210229 -0.000212158 -0.0120759" />
      </xacro:if>
      <xacro:unless value="${using_capsule_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://talos_description/meshes/torso/torso_1.STL" scale="1 1 1"/>
        </geometry>
        </collision>
      </xacro:unless>
    </link>

    <joint name="${name}_1_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${name}_1_link"/>
      <!-- XXX AS, The kinematic chain order for the torso was reversed manually. This value does not match the CAD model. XXX -->
      <origin xyz="${0.0 + torso_1_joint_x_offset} ${0.0 + torso_1_joint_y_offset} ${0.0722 + torso_1_joint_z_offset}"
              rpy="${0.00000 * deg_to_rad + torso_1_joint_roll_offset} ${0.00000 * deg_to_rad + torso_1_joint_pitch_offset} ${0.00000 * deg_to_rad + torso_1_joint_yaw_offset}"/>
      <axis xyz="0 0 1" />
      <limit lower="${-72.00000 * deg_to_rad}" upper="${72.00000 * deg_to_rad}"
             effort="${torso_max_effort}" velocity="${torso_max_vel}" />
      <dynamics damping="1.0" friction="1.0"/>

      <!-- <safety_controller k_position="20"
                         k_velocity="20"
                         soft_lower_limit="${-15.0 * deg_to_rad + torso_eps}"
                         soft_upper_limit="${ 45.0 * deg_to_rad - torso_eps}" /> -->
    </joint>

    <!--************************-->
    <!--        BASE_LINK       -->
    <!--************************-->
    <link name="base_link">
      <xacro:call macro="base_link_inertial" />

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://talos_description/meshes/torso/base_link.STL" scale="1 1 1"/>
        </geometry>
        <material name="LightGrey" />
      </visual>

      <xacro:if value="${using_capsule_collision}">
        <xacro:capsule-collision e1="-0.0485657 0.111601 -0.05811" e2="-0.0490399 -0.110849 -0.0575714" rad="0.16382936354183916" clen="0.22245096803647357" rpy="1.56838 -0.00213179 -0.00212663" mid="-0.0488028 0.000376009 -0.0578407" />
      </xacro:if>
      <xacro:unless value="${using_capsule_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://talos_description/meshes/torso/base_link_collision.STL" scale="1 1 1"/>
          </geometry>
        </collision>
      </xacro:unless>
    </link>

    <joint name="${name}_2_joint" type="revolute">
      <parent link="${name}_1_link"/>
      <child link="${name}_2_link"/>
      <origin xyz="${0.0 + torso_2_joint_x_offset} ${0.0 + torso_2_joint_y_offset} ${0.0 + torso_2_joint_z_offset}"
              rpy="${0.00000 * deg_to_rad + torso_2_joint_roll_offset} ${0.00000 * deg_to_rad + torso_2_joint_pitch_offset} ${0.00000 * deg_to_rad + torso_2_joint_yaw_offset}"/>
      <axis xyz="0 1 0" />
      <limit lower="${-13.0 * deg_to_rad}" upper="${42.0 * deg_to_rad}"
             effort="${torso_max_effort}" velocity="${torso_max_vel}"/>
      <dynamics friction="1.0" damping="1.0"/>

      <!-- <safety_controller k_position="20"
                          k_velocity="20"
                          soft_lower_limit="${-75.00000 * deg_to_rad + eps_radians}"
                          soft_upper_limit="${75.00000 * deg_to_rad - eps_radians}" /> -->

    </joint>

    <xacro:talos_imu name="imu" parent="${name}_2_link" update_rate="100.0">
    <origin xyz="${0.04925 + torso_imu_x_offset} ${0.0 + torso_imu_y_offset} ${0.078 + torso_imu_z_offset}"
	    rpy="${(180.0 + torso_imu_roll_offset)*deg_to_rad} ${(0.0 + torso_imu_pitch_offset)*deg_to_rad} ${(90.0 + torso_imu_pitch_offset)*deg_to_rad}"/>
    </xacro:talos_imu>


    <gazebo reference="${name}_1_link">
        <mu1>0.9</mu1>
        <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="${name}_2_link">
        <mu1>0.9</mu1>
        <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="base_link">
        <mu1>0.9</mu1>
        <mu2>0.9</mu2>
    </gazebo>

    <gazebo reference="${name}_1_joint">
        <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>
    <gazebo reference="${name}_2_joint">
        <implicitSpringDamper>1</implicitSpringDamper>
        <provideFeedback>1</provideFeedback>
    </gazebo>

  </xacro:macro>

</robot>
