gripper_left_controller:
  ros__parameters:  
    joints:
      - gripper_left_joint
    command_interfaces:
      - position
    state_interfaces:
      - position      
    constraints:
      goal_time: &goal_time_constraint 0.6
      stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
      gripper_left_joint:
        goal: &goal_pos_constraint 0.02