gripper_right_controller:
  ros__parameters:
    joints:
      - gripper_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position      
    constraints:
      goal_time: &goal_time_constraint 0.6
      stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
      gripper_right_joint:
        goal: &goal_pos_constraint 0.02
