leg_right_controller:
  ros__parameters:
    joints:
      - leg_right_1_joint
      - leg_right_2_joint
      - leg_right_3_joint
      - leg_right_4_joint
      - leg_right_5_joint
      - leg_right_6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position        
    constraints:
      goal_time: &goal_time_constraint 0.6
      stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
      arm_right_1_joint:
        goal: &goal_pos_constraint 0.02
      arm_right_2_joint:
        goal: *goal_pos_constraint
      arm_right_3_joint:
        goal: *goal_pos_constraint
      arm_right_4_joint:
        goal: *goal_pos_constraint
      arm_right_5_joint:
        goal: *goal_pos_constraint
      arm_right_6_joint:
        goal: *goal_pos_constraint

