torso_controller:
  ros__parameters:
    joints:
      - torso_1_joint
      - torso_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    constraints:
      goal_time: &goal_time_constraint 0.6
      stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
      torso_1_joint:
        goal: &goal_pos_constraint 0.02
      torso_2_joint:
        goal: *goal_pos_constraint

