<?xml version="1.0"?>
<!--

  Copyright (c) 2016, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!--File includes-->
  <xacro:include filename="$(find talos_description)/urdf/deg_to_rad.xacro" />
  <xacro:include filename="$(find talos_description)/urdf/arm/wrist.transmission.xacro" />

  <!--Constant parameters-->
  <xacro:property name="wrist_friction"       value="1.0" />
  <xacro:property name="wrist_damping"        value="1.0" />
  <xacro:property name="wrist_1_max_vel"      value="1.95" />
  <xacro:property name="wrist_2_max_vel"      value="1.76" />
  <xacro:property name="wrist_3_max_vel"      value="1.76" />
  <xacro:property name="wrist_1_max_effort"   value="20.0" />
  <xacro:property name="wrist_2_max_effort"   value="8.0" />
  <xacro:property name="wrist_3_max_effort"   value="8.0" />
  <xacro:property name="wrist_eps"          value="0.02" />


  <xacro:macro name="talos_wrist" params="name parent side reflect using_capsule_collision">
    <xacro:unless value="$(arg test)">
      <xacro:include filename="$(find talos_description_calibration)/urdf/calibration/arm_${side}.xacro" />
    </xacro:unless>
    <xacro:if value="$(arg test)">
      <xacro:include filename="$(find talos_description)/test/calibration/arm_${side}.xacro" />
    </xacro:if>

    <!--************************-->
    <!--        WRIST           -->
    <!--************************-->
    <link name="${name}_${side}_5_link">
      <xacro:call macro="${name}_${side}_5_link_inertial" />

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://talos_description/meshes/arm/arm_5.STL" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="LightGrey" />
      </visual>

      <xacro:if value="${using_capsule_collision}">
        <xacro:if value="${side == 'left'}">
	  <xacro:capsule-collision e1="-2.13964e-05 0.000999035 0.0358616" e2="0.000145615 0.0012191 0.121451" rad="0.077412213480368891" clen="0.085589949413547098" rpy="-0.00257122 0.0019513 -2.50861e-06" mid="6.21094e-05 0.00110907 0.0786563" />
        </xacro:if>
        <xacro:if value="${side == 'right'}">
	  <xacro:capsule-collision e1="-2.13964e-05 -0.000999035 0.0358616" e2="0.000145615 -0.0012191 0.121451" rad="0.077412213480368891" clen="0.085589949413547098" rpy="0.00257122 0.0019513 2.50861e-06" mid="6.21094e-05 -0.00110907 0.0786563" />
        </xacro:if>
      </xacro:if>

      <xacro:unless value="${using_capsule_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://talos_description/meshes/arm/arm_5_collision.STL" scale="1 ${reflect} 1"/>
          </geometry>
        </collision>
      </xacro:unless>

    </link>

    <joint name="${name}_${side}_5_joint" type="revolute">
      <parent link="${parent}" />
      <child link="${name}_${side}_5_link" />
      <origin xyz="${-0.02000 + arm_5_joint_x_offset} ${0.00000 + arm_5_joint_y_offset} ${-0.26430 + arm_5_joint_z_offset}"
              rpy="${0.00000 * deg_to_rad + arm_5_joint_roll_offset} ${0.00000 * deg_to_rad + arm_5_joint_pitch_offset} ${0.00000 * deg_to_rad + arm_5_joint_yaw_offset}"/>
      <axis xyz="0 0 1" />
      <limit lower="${-144.0 * deg_to_rad}" upper="${144.0 * deg_to_rad}" effort="${wrist_1_max_effort}" velocity="${wrist_1_max_vel}" />
      <dynamics friction="${wrist_friction}" damping="${wrist_damping}"/>
<!--       <safety_controller k_position="20"
                          k_velocity="20"
                          soft_lower_limit="${-145.00000 * deg_to_rad + wrist_eps}"
                          soft_upper_limit="${145.00000 * deg_to_rad - wrist_eps}" /> -->

    </joint>

    <link name="${name}_${side}_6_link">
      <xacro:call macro="${name}_${side}_6_link_inertial" />

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://talos_description/meshes/arm/arm_6.STL" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="LightGrey" />
      </visual>

      <xacro:if value="${using_capsule_collision}">
        <xacro:if value="${side == 'left'}">
	  <xacro:capsule-collision e1="3.71733e-07 -0.000248227 -0.00766634" e2="5.46154e-05 -8.61821e-05 0.00107298" rad="0.044402592090813625" clen="0.0087409825962203314" rpy="-0.0185399 0.00620572 -5.75286e-05" mid="2.74936e-05 -0.000167204 -0.00329668" />

        </xacro:if>
        <xacro:if value="${side == 'right'}">
	  <xacro:capsule-collision e1="3.71733e-07 0.000248227 -0.00766634" e2="5.46154e-05 8.61821e-05 0.00107298" rad="0.044402592090813625" clen="0.0087409825962203314" rpy="0.0185399 0.00620572 5.75286e-05" mid="2.74936e-05 0.000167204 -0.00329668" />
        </xacro:if>
      </xacro:if>

      <xacro:unless value="${using_capsule_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://talos_description/meshes/arm/arm_6_collision.STL" scale="1 ${reflect} 1"/>
          </geometry>
        </collision>
      </xacro:unless>
    </link>

    <joint name="${name}_${side}_6_joint" type="revolute">
      <parent link="${name}_${side}_5_link" />
      <child link="${name}_${side}_6_link" />
      <origin xyz="${0.00000 + arm_6_joint_x_offset} ${0.00000 + arm_6_joint_y_offset} ${0.00000 + arm_6_joint_z_offset}"
              rpy="${0.00000 * deg_to_rad + arm_6_joint_roll_offset} ${0.00000 * deg_to_rad + arm_6_joint_pitch_offset} ${0.00000 * deg_to_rad + arm_6_joint_yaw_offset}"/>
      <axis xyz="1 0 0" />
      <limit lower="${-78.5 * deg_to_rad}" upper="${78.5 * deg_to_rad}" effort="${wrist_2_max_effort}" velocity="${wrist_2_max_vel}" />
      <dynamics friction="${wrist_friction}" damping="${wrist_damping}"/>
<!--       <safety_controller k_position="20"
                          k_velocity="20"
                          soft_lower_limit="${-80.00000 * deg_to_rad + eps_radians}"
                          soft_upper_limit="${80.00000 * deg_to_rad - eps_radians}" /> -->

    </joint>

    <link name="${name}_${side}_7_link">
      <xacro:call macro="${name}_${side}_7_link_inertial" />

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://talos_description/meshes/arm/arm_7.STL" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>

      <xacro:if value="${using_capsule_collision}">
        <xacro:if value="${side == 'left'}">
	  <xacro:capsule-collision e1="-3.67844e-05 -8.9312e-05 -0.0167866" e2="1.80245e-05 -1.49283e-05 -0.0702192" rad="0.048804145966408037" clen="0.05343267786175529" rpy="-3.1402 0.00102576 -1.27005" mid="-9.37996e-06 -5.21201e-05 -0.0435029" />
        </xacro:if>
        <xacro:if value="${side == 'right'}">
	  <xacro:capsule-collision e1="-3.67844e-05 8.9312e-05 -0.0167866" e2="1.80245e-05 1.49283e-05 -0.0702192" rad="0.048804145966408037" clen="0.05343267786175529" rpy="3.1402 0.00102576 1.27005" mid="-9.37996e-06 5.21201e-05 -0.0435029" />
        </xacro:if>
      </xacro:if>

      <xacro:unless value="${using_capsule_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://talos_description/meshes/arm/arm_7_collision.STL" scale="1 ${reflect} 1"/>
          </geometry>
        </collision>
      </xacro:unless>

    </link>

    <joint name="${name}_${side}_7_joint" type="revolute">
      <parent link="${name}_${side}_6_link" />
      <child link="${name}_${side}_7_link" />
      <origin xyz="${0.00000 + arm_7_joint_x_offset} ${0.00000 + arm_7_joint_y_offset} ${0.00000 + arm_7_joint_z_offset}"
              rpy="${0.00000 * deg_to_rad + arm_7_joint_roll_offset} ${0.00000 * deg_to_rad + arm_7_joint_pitch_offset} ${0.00000 * deg_to_rad + arm_7_joint_yaw_offset}"/>
      <axis xyz="0 1 0" />
      <limit lower="${-39.0 * deg_to_rad}" upper="${39.0 * deg_to_rad}" effort="${wrist_3_max_effort}" velocity="${wrist_3_max_vel}"/>
      <dynamics friction="${wrist_friction}" damping="${wrist_damping}"/>
<!--       <safety_controller k_position="20"
                          k_velocity="20"
                          soft_lower_limit="${-40.00000 * deg_to_rad + eps_radians}"
                          soft_upper_limit="${40.00000 * deg_to_rad - eps_radians}" /> -->


    </joint>

    <gazebo reference="${name}_${side}_5_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="${name}_${side}_6_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="${name}_${side}_7_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
      <material>Gazebo/FlatBlack</material>
    </gazebo>

    <gazebo reference="${name}_${side}_5_joint">
        <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>
    <gazebo reference="${name}_${side}_6_joint">
        <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>
    <gazebo reference="${name}_${side}_7_joint">
        <implicitSpringDamper>1</implicitSpringDamper>
        <provideFeedback>1</provideFeedback>
    </gazebo>


  </xacro:macro>

</robot>
